document.writeln("<div id=\'footer\'>");
document.writeln("        <div class=\'margin\'>");
document.writeln("            <div class=\'footer-t\'>");
document.writeln("                <a href=\'##\' style=\'color: #737373; font-family: Microsoft YaHei\'>");
document.writeln("                opyright ©2019 南京视客网络科技有限公司 版权所有. 法律顾问：秦在丛（执业编号：13201200411564699） ");
document.writeln("                </a>");
document.writeln("                <div>");
document.writeln("                    <a href=\'##\'>苏ICP备12054666号</a>");
document.writeln("                    <a href=\'##\'>ICP经营许可证：苏B2-20170205</a>");
document.writeln("                    <a href=\'##\'> 医疗器械经营许可证：苏宁食药监械经营许20170464号</a>");
document.writeln("                    <a href=\'##\'>互联网药品信息服务资格证书编号：(苏)-经营性-2017-0005</a>");
document.writeln("                    <a target=\'_blank\' href=\'http://www.beian.gov.cn/portal/registerSystemInfo?recordcode=32010402000492\'>");
document.writeln("                    <img src=\'https://images.vsigo.cn/zhuanti/playcolor2018_04/police.png\' style=\'margin-right:5px;position:relative;top:5px;\'>苏公网安备 32010402000492号</a>");
document.writeln("                    ");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("            <div class=\'footer-b\'>");
document.writeln("                <ul>");
document.writeln("                    <li><a href=\'##\' class=\'zhs_pic dsxh1\'></a></li>");
document.writeln("                    <li><a href=\'##\' class=\'zhs_pic dsxh2\'></a></li>");
document.writeln("                    <li><a href=\'##\' class=\'zhs_pic dsxh3\'></a></li>");
document.writeln("                    <li><a href=\'##\' class=\'zhs_pic dsxh4\'></a></li>");
document.writeln("                    <li><a href=\'##\' class=\'zhs_pic dsxh5\'></a></li>");
document.writeln("                    <li><a href=\'##\' class=\'zhs_pic dsxh6\'></a></li>");
document.writeln("                    <li><a href=\'##\' class=\'zhs_pic dsxh7\'></a></li>");
document.writeln("                </ul>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("    </div>");